name: Run Daily Script

on:
  schedule:
    - cron: '30 15 * * *'  # 11:30 AM EST (15:30 UTC)
  workflow_dispatch:       # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests pytz

      - name: Run script
        run: python worker.py
